"""Re-embed Qdrant chunks after switching embedding provider.

Vectors generated by different models (e5-large vs OpenAI text-embedding-3-small)
are NOT semantically interchangeable, even at the same dimension.

Usage:
    docker exec ia_backend python /app/re_embed_qdrant.py [--tenant demo] [--batch 50]

Reads each point from Qdrant, re-embeds its `text` payload with the active
EMBEDDING_PROVIDER, and updates the vector in place. Payload (chunk_id, doc_id,
filename, etc.) is preserved.

Safe to re-run — idempotent. Skips collections that don't exist.
"""

import argparse
import logging
import sys
import time

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("re_embed")


def re_embed_collection(collection: str, batch_size: int) -> tuple[int, int]:
    """Re-embed all points in a Qdrant collection. Returns (re_embedded, errors)."""
    from qdrant_client import QdrantClient
    from qdrant_client.models import PointVectors
    from core.config import settings
    from services.embeddings import embed_passage, _is_openai

    client = QdrantClient(host=settings.qdrant_host, port=settings.qdrant_port)

    try:
        info = client.get_collection(collection)
    except Exception as e:
        log.warning("collection %s not found: %s", collection, e)
        return 0, 0

    total_points = info.points_count or 0
    if total_points == 0:
        log.info("collection %s is empty, skipping", collection)
        return 0, 0

    log.info("re-embedding %d points from %s (provider=%s)",
             total_points, collection, "openai" if _is_openai() else "local")

    re_embedded = 0
    errors = 0
    offset = None

    while True:
        points, offset = client.scroll(
            collection_name=collection,
            limit=batch_size,
            offset=offset,
            with_payload=True,
            with_vectors=False,
        )
        if not points:
            break

        # Extract texts in batch
        ids = []
        texts = []
        skip_count = 0
        for p in points:
            txt = (p.payload or {}).get("text") or ""
            if not txt:
                skip_count += 1
                continue
            ids.append(p.id)
            texts.append(txt)
        if skip_count:
            log.warning("skipped %d points without 'text' payload", skip_count)

        # Batch embed
        from services.embeddings import embed_batch
        t0 = time.monotonic()
        vectors = embed_batch(texts, is_query=False)
        dt = (time.monotonic() - t0) * 1000

        # Update vectors in Qdrant
        ok_payloads = []
        for pid, vec in zip(ids, vectors):
            if vec is None:
                errors += 1
                log.error("embedding failed for point id=%s", pid)
                continue
            ok_payloads.append(PointVectors(id=pid, vector=vec))

        if ok_payloads:
            client.update_vectors(collection_name=collection, points=ok_payloads)
            re_embedded += len(ok_payloads)

        log.info("batch done: %d re-embedded in %.0fms (cumulative %d/%d)",
                 len(ok_payloads), dt, re_embedded, total_points)

        if offset is None:
            break

    return re_embedded, errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tenant", default="demo", help="Tenant ID prefix for collections")
    parser.add_argument("--batch", type=int, default=50, help="Batch size for embedding")
    parser.add_argument("--collections", nargs="+", default=None,
                        help="Override collection list (default: {tenant}_docs, {tenant}_intenciones)")
    args = parser.parse_args()

    if args.collections:
        targets = args.collections
    else:
        targets = [f"{args.tenant}_docs", f"{args.tenant}_intenciones"]

    log.info("targets: %s", targets)
    total_re = 0
    total_err = 0
    t0 = time.monotonic()
    for c in targets:
        try:
            re, er = re_embed_collection(c, args.batch)
        except Exception as e:
            log.exception("failed on collection %s: %s", c, e)
            return 1
        total_re += re
        total_err += er
    dt = time.monotonic() - t0

    log.info("=" * 60)
    log.info("DONE: %d re-embedded, %d errors in %.1fs", total_re, total_err, dt)
    return 0 if total_err == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
